spring.application.name=secondhand

spring.datasource.url=jdbc:mysql://localhost:3306/secondhand
spring.datasource.password=secondhand123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=secondhand

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=rAqHLg8/eVgVlUIdBT8/2UFbHrlo+cBZsTSUNFvodI0=
jwt.expire=86400000

server.port=8080
